export interface FormData {
  // Q2-0
  userName: string;
  userTitle: string;
  userAgeRange: string;
  userHeight: string;
  userIndustry: string;
  userCity: string;
  userPhone: string;
  // Q2-1
  projectLocation: string;
  projectName: string;
  // Q2-2
  projectType: string;
  projectArea: string;
  houseType: string;
  houseCondition: string;
  // Q2-3
  budgetStandard: string;
  budgetSubStandard: string;
  // Q2-4
  floorPlanUploaded: boolean;
  // Q2-5
  lighting: string;
  ceilingHeight: string;
  ventilation: string;
  noise: string;
  // Q2-6
  role: string;
  favoriteSpace: string[];
  additionalMembers: string[];
  daughterSpaces: string[];
  sonSpaces: string[];
  catSpaces: string[];
  dogSpaces: string[];
  // Q2-7
  collaboration: string;
  involvement: string;
  // Q2-8
  timeline: string;
  // Q2-9
  coreSpaces: string;
  childGrowth: string;
  guestStay: string;
  futureChanges: string;
  // Q2-10
  cookingHabit: string;
  secondKitchen: string;
  // Q2-11
  diningCount: string;
  festivalDiningCount: string;
  // Q2-12
  partyFrequency: string;
  // Q2-13
  livingRoomActivity: string;
  livingRoomFeature: string[];
  // Q2-14
  storageFocus: string[];
  // Q2-15
  dryWetSeparation: string;
  // Q2-16
  bottomLine: string[];
  // Q2-17
  fengshui: string;
  // Q2-18
  smartHome: string;
  smartHomeOptions: string[];
  // Q2-19
  comfortSystems: string[];
  // Q2-20
  devices: string[];
  // Q2-21
  accessibility: string;
  oldFurniture: string;
  otherNeeds: string;
  otherNeedsOptions: string[];
  // Contract
  contractAccepted?: boolean;
  contractSignatureData?: string;
  contractCustomText?: string;
}

export const initialFormData: FormData = {
  userName: '',
  userTitle: '',
  userAgeRange: '',
  userHeight: '',
  userIndustry: '',
  userCity: '',
  userPhone: '',
  projectLocation: '',
  projectName: '',
  projectType: '',
  projectArea: '',
  houseType: '',
  houseCondition: '',
  budgetStandard: '',
  budgetSubStandard: '',
  floorPlanUploaded: false,
  lighting: '',
  ceilingHeight: '',
  ventilation: '',
  noise: '',
  role: '',
  favoriteSpace: [],
  additionalMembers: [],
  daughterSpaces: [],
  sonSpaces: [],
  catSpaces: [],
  dogSpaces: [],
  collaboration: '',
  involvement: '',
  timeline: '',
  coreSpaces: '1客厅1餐厅1主卧室1主卫浴室1公卫浴室',
  childGrowth: '',
  guestStay: '',
  futureChanges: '',
  cookingHabit: '',
  secondKitchen: '',
  diningCount: '',
  festivalDiningCount: '',
  partyFrequency: '',
  livingRoomActivity: '',
  livingRoomFeature: [],
  storageFocus: [],
  dryWetSeparation: '',
  bottomLine: [],
  fengshui: '',
  smartHome: '',
  smartHomeOptions: [],
  comfortSystems: [],
  devices: [],
  accessibility: '',
  oldFurniture: '',
  otherNeeds: '',
  otherNeedsOptions: [],
  contractAccepted: false,
  contractSignatureData: '',
  contractCustomText: '',
};
